# Form implementation generated from reading ui file 'res/untitled3.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from random import choices


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 371, 95))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.val_frame_width = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.val_frame_width.setObjectName("val_frame_width")
        self.val_frame_width.setMinimum(1)
        self.val_frame_width.setMaximum(11)
        self.gridLayout.addWidget(self.val_frame_width, 2, 2, 1, 1)
        self.val_jackal = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.val_jackal.setReadOnly(False)
        self.val_jackal.setObjectName("val_jackal")
        self.val_jackal.setMinimum(1)
        self.val_jackal.setMaximum(100)
        self.gridLayout.addWidget(self.val_jackal, 0, 2, 1, 1)
        self.jackal = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.jackal.setObjectName("jackal")
        self.gridLayout.addWidget(self.jackal, 0, 0, 1, 1)
        self.val_frame = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.val_frame.setObjectName("val_frame")
        self.val_frame.setMinimum(10)
        self.val_frame.setMaximum(150)
        self.gridLayout.addWidget(self.val_frame, 1, 2, 1, 1)
        self.frame_width = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.frame_width.setObjectName("frame_width")
        self.gridLayout.addWidget(self.frame_width, 2, 0, 1, 1)
        self.frame = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.edit_jackal = QtWidgets.QSlider(parent=self.gridLayoutWidget)
        self.edit_jackal.setMinimum(1)
        self.edit_jackal.setMaximum(100)
        self.edit_jackal.setPageStep(10)
        self.edit_jackal.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.edit_jackal.setTickPosition(QtWidgets.QSlider.TickPosition.TicksAbove)
        self.edit_jackal.setObjectName("edit_jackal")
        self.gridLayout.addWidget(self.edit_jackal, 0, 1, 1, 1)
        self.edit_frame = QtWidgets.QSlider(parent=self.gridLayoutWidget)
        self.edit_frame.setMinimum(10)
        self.edit_frame.setMaximum(150)
        self.edit_frame.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.edit_frame.setTickPosition(QtWidgets.QSlider.TickPosition.TicksAbove)
        self.edit_frame.setObjectName("edit_frame")
        self.gridLayout.addWidget(self.edit_frame, 1, 1, 1, 1)
        self.edit_frame_width = QtWidgets.QSlider(parent=self.gridLayoutWidget)
        self.edit_frame_width.setMinimum(1)
        self.edit_frame_width.setMaximum(11)
        self.edit_frame_width.setPageStep(1)
        self.edit_frame_width.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.edit_frame_width.setTickPosition(QtWidgets.QSlider.TickPosition.TicksAbove)
        self.edit_frame_width.setObjectName("edit_frame_width")
        self.gridLayout.addWidget(self.edit_frame_width, 2, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(8, 160, 371, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._update = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self._update.setObjectName("_update")
        self.horizontalLayout.addWidget(self._update)
        self._reset = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self._reset.setObjectName("_reset")
        self.horizontalLayout.addWidget(self._reset)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", choices(["Настройки", "На стройке"], weights=[0.9, 0.1], k=1)[0]))
        self.jackal.setText(_translate("Form", "Шакальность по умолчанию"))
        self.frame_width.setText(_translate("Form", "Обводка рамки демика"))
        self.frame.setText(_translate("Form", "Рамка демика"))
        self._update.setText(_translate("Form", "Обновить прошивку"))
        self._reset.setText(_translate("Form", "Сброс до заводских"))
